name: ci
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
          registry-url: https://registry.npmjs.org
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.16.0
      - run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Set version
        run: pnpm version --no-git-tag-version ${{ github.event.release.tag_name }}

      - name: Publish package
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
